#!/bin/sh
./RT scenes_xml/group_5.xml &
./RT scenes_xml/group_5.xml &
./RT scenes_xml/group_5.xml &
./RT scenes_xml/group_5.xml &
./RT scenes_xml/group_5.xml &
./RT scenes_xml/group_5.xml &
./RT scenes_xml/group_5.xml &
./RT scenes_xml/group_5.xml &
./RT scenes_xml/group_5.xml &
./RT scenes_xml/group_5.xml &
./RT scenes_xml/group_5.xml &
./RT scenes_xml/group_5.xml &
./RT scenes_xml/group_5.xml &
./RT scenes_xml/group_5.xml &
./RT scenes_xml/group_5.xml &
./RT scenes_xml/group_5.xml &
./RT scenes_xml/group_5.xml &
./RT scenes_xml/group_5.xml &
./RT scenes_xml/group_5.xml &
./RT scenes_xml/group_5.xml &
./RT scenes_xml/group_5.xml &
./RT scenes_xml/group_5.xml &
./RT scenes_xml/group_5.xml &
./RT scenes_xml/group_5.xml &
./RT scenes_xml/group_5.xml &
